### ISSUE TITLE
Create Theme

### ISSUE THREAD

**Issue by oli-lane** [hack4impact-calpoly/ecologistics-web-scraper#10]
Go to the Ecologistics website and see what the primary and secondary colors are. If there are any accent colors, make note of them too. Modify the tailwind.config.js to add these theme colors. At your discretion you can modify the colors (make them lighter/darker , add a new color that fits with the main colors, etc.), whatever you think looks good! 

Requirements:

- [x] Primary and secondary colors
- [x] At least two other accent/neutral colors that could be used in the project
- [x] Documentation on how to incorporate theme with shadcn

Research how to implement these colors in our shadcn components, and post what you find as a comment to this issue.

**Comment by SilverXer0** [comment]
Primary: 25.1 86.6 56.1% (Ecologistics orange, used for prominent text/buttons)
Secondary:  147.3 24.1 49.9% (I lightened up the dark green, it used to be 26.9% L)
Accent/Neutral: [160 44.6 80.2%] (lighter blue/green to contrast the darker green) , [128.4 48.7 62.5%] (regular green)
[0 0 51%] - the shade of gray in the EcoLogistics logo and text used

The setup for using shadCn with tailwind has already been done, now we just have to incorporate it. With our colors somewhat set up, we just need to change classNames. 'Default' refers to the background color and 'foreground' refers to the text color. **https://ui.shadcn.com/docs/theming** includes a lot of information on how to define the className, but it essentially takes the name of what the variable is called in tailwind.config. bg refers to background and text refers to the text color. If we wanted to change the 'home' text in page.tsx, we would just have to add a className to the header with the word labeled "className = "bg-primary text-primary-foreground." If I changed the primary foreground to 0 0 51%, then the text color matches the EcoLogistics gray used in their logo. ShadCn contains a lot of default colors for labels like <card>, <button>, etc, so you have to manually add these into the color section with a variable name and change the color in global.css. Then, you can implement them normally in a tsx file.
