### ISSUE TITLE
Web Scraping Approach (2 person)

### ISSUE THREAD

**Issue by oli-lane** [hack4impact-calpoly/ecologistics-web-scraper#117]
**Dev 1:**
On the about page, look at the current details of the web scraping approach for SLO county, and create a list of the steps, including all the entities data is coming from (county calendar, specific agendas, state clearing house, etc), and what information is extracted from each entity. Be sure to consult the codebase and update the steps (if necessary) to ensure they reflect how the web scraping is currently done.  Additionally, include the order in which the information is extracted. In the end it should look something like:

1. web scraping request
2. ...
3. ...
4. update table

NOTE: please checkin with Ryan and Oli before dev 2 starts the diagram

**Dev 2:**
After dev 1 is finished, use the steps to create a diagram to visualize the data flow of web scraping operations. Use shapes and arrows, and be sure to use the same green that we've been using (in the source code). From the diagram, a user should be able to see what information we're getting from each source, and when in the process we get it.

We recommend you use figma, but whichever tool you use be sure to link your template in the `docs` folder somewhere to support the addition of future counties.

Here are some basic guidelines your diagram should follow:

- Shapes (circles for example) represent entities where we draw information from
- Arrows from A to B represent the information that's being extracted from A and being sent to B

Requirements:

- [ ] Diagram is landscape
- [ ] Entity shapes are the primary green color we've been using
- [ ] Diagram includes icons (to make it pretty) for each entity that make sense
- [ ] Arrows connect each entity
- [ ] Diagram reflects the same data flow and web scraping operations as our code
- [ ] Data flow goes left to right

Some diagrams to get you started:

![Image](https://github.com/hack4impact-calpoly/ecologistics-web-scraper/assets/91087587/887ade52-f343-4068-9d6b-fdacd0d4ff71)

![Image](https://github.com/hack4impact-calpoly/ecologistics-web-scraper/assets/91087587/37b56870-3a97-4ace-9e4e-2944d4ae6f9d)

**Comment by ryanchansf** [comment]
Dev 1: Isha
Dev 2: Wesley
