### ISSUE TITLE
Research: setting up NextAuth.js

### ISSUE THREAD

**Issue by ryanchansf** [hack4impact-calpoly/ecologistics-web-scraper#7]
We'll be using the **[NextAuth.js](https://next-auth.js.org/?_gl=1*1ekrk8x*_gcl_au*MzIxMjkzNy4xNzA1OTUxODk4)** library to handle authentication and authorization in our app. For our current purposes, we'll be focusing on figuring out how to integrate AuthN for our log-in and sign-up pages. In this research task, figure out

- [x] How to set up NextAuth.js in our Next.js frontend
- [x] Steps to integrate it with our log-in and sign-up pages
- [x] Any other notes about how it works

For this task, document everything as a comment to this issue. Include screenshots/code snippets if necessary!

BONUS: find out if there's a way to integrate this with API endpoints that we might write in python. This might require some research on JWTs, and how they can be sent from our Next.js frontend to our backend (likely will be written in python)

**Comment by eewalia12** [comment]
I added the research I found to this document!

https://docs.google.com/document/d/1bMXZSdW2a68goYeFRp806aaMudDrbO72P4sQ-wZ0aoI/edit?usp=sharing

**Comment by ryanchansf** [comment]
> I added the research I found to this document!
> 
> https://docs.google.com/document/d/1bMXZSdW2a68goYeFRp806aaMudDrbO72P4sQ-wZ0aoI/edit?usp=sharing

Sweet! Thanks for doing this. Documentation looks good and we can use this in our next task to set it up!

**Comment by sophiapeckner** [comment]
Also added my research to the Google Doc. See step (3) "Below code from here (utilizes JWT Access Tokens)" and "Django x. NextAuth" section.
