### ISSUE TITLE
Page numbers for pagination

### ISSUE THREAD

**Issue by oli-lane** [hack4impact-calpoly/ecologistics-web-scraper#71]
Using the [shadcn tasks example](https://ui.shadcn.com/examples/tasks) (source code
[here](https://github.com/shadcn-ui/ui/tree/main/apps/www/app/examples/tasks
)) as a reference, add page numbers to the pagination, as well as a rows per page option. In the end, it should look like this:

![Image](https://github.com/hack4impact-calpoly/ecologistics-web-scraper/assets/91087587/175c52e4-5885-4aca-89dc-45dace8e5d40)

Requirements:

- [ ] Rows per page functionality
- [ ] Displays current page
- [ ] Buttons to navigate to first or last page

**Comment by Robert303V** [comment]
Here's the link to the tutorial I used for setting up the data table, it should help clarify how the pagination is currently working.

https://ui.shadcn.com/docs/components/data-table
