### ISSUE TITLE
Research task manager

### ISSUE THREAD

**Issue by ryanchansf** [hack4impact-calpoly/ecologistics-web-scraper#93]
The webscraper will run automatically once a week. Research some services that we could use to schedule the webscraping tasks to run, ideally ones compatible (or through) AWS.

Put your research into a Google Doc and link it as a comment to this issue.

**Comment by eewalia12** [comment]
https://docs.google.com/document/d/1ZMad0LWget0eD0yPMXUzMqR3CmNGyqONdj0kA62eTbM/edit?usp=sharing

**Comment by Parshana007** [comment]
https://docs.google.com/document/d/1jdbALeOXF3dDMI7dWOaYfTO0sSkFmm9uuQxKy0twb7k/edit?usp=sharing

**Comment by sanjanachecker** [comment]
https://docs.google.com/document/d/1S9o369Ivd2MSJyRQg49vOH27deLJy9ZntsQVjkulHCw/edit?usp=sharing

**Comment by ryanchansf** [comment]
Great job with the research guys! It looks like spinning up a Lambda with EventBridge seems like the way to go based on the research you all did. Oli and I will continue to hash out the details for how this will all work with our AWS deployment, but this gives us a great direction for where to go with our scheduled webscraping events. Thanks guys!
